### ISSUE TITLE
Implement WebElement wrapper

### ISSUE THREAD

**Issue by RomanIovlev** [jdi-testing/jdi-light-csharp#1]
1) Create UIElement that implements [WebElement](https://github.com/jdi-testing/jdi-light/blob/master/jdi-light/src/main/java/com/epam/jdi/light/elements/base/UIElement.java )
2) Create [PageFactory for PageObjects initialization](https://github.com/jdi-testing/jdi-light/blob/master/jdi-light/src/main/java/com/epam/jdi/light/elements/init/PageFactory.java )
3) Create [WebDriverFactory for work with WebDriver](https://github.com/jdi-testing/jdi-light/blob/master/jdi-light/src/main/java/com/epam/jdi/light/driver/WebDriverFactory.java)

For Examples see [here](https://github.com/jdi-testing/jdi-light/tree/master/jdi-light-examples)

┆Attachments: <a href="https:&#x2F;&#x2F;github.com&#x2F;jdi-testing&#x2F;jdi-light-csharp&#x2F;issues&#x2F;1">#1 Implement WebElement wrapper</a>

**Comment by elv1s42** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Test item](https://trello.com/c/X2wBnssZ/1-test-item)

**Comment by elv1s42** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implement WebElement wrapper](https://trello.com/c/HvVe1KvB/6-implement-webelement-wrapper)
