### ISSUE TITLE
Create documentation for DateTimeSelector element

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light-csharp#122]
Use Checkbox element as an example

**Comment by margarita-ivanova-epam** [comment]
All elements of 'Input type date/week/month/time/datetime' are DateTimeSelector elements. Not sure whether we need to highlight this separately. Suggest to make the whole section 'DateTime Selector' with sub-sections containing examples of those implementations.

**Comment by AlexeyGirin** [comment]
Add declaration for C# code example section

**Comment by AlexeyGirin** [comment]
Demo has been done
