### ISSUE TITLE
Add more tests for JDropDown in Java

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light-csharp#138]
Compare with C# and add more tests for Java if needed

**Comment by AlexeyGirin** [comment]
1. Investigate the opportunity to make enumeration for 1
2. Investigate test fails
Consult w/ @RomanIovlev

**Comment by antonfilichkin** [comment]
**Droplist** - custom dropdown implementation (annotated by **@JDropdown**) needs implementation in **JDI-light-html**, with possible usage of the same **Dropdown Interface**. 
There is also need for @JMultiDropdown annotation  to handle non-HTML5 implementations of **MultiDropdowns** (ex. Vegetables on [Metals&Colors Page](https://epam.github.io/JDI/metals-colors.html)) or possibility to handle custom **MultiDropdowns** with **@JDropdown** annotation also.
Group of selectors are much the same - maybe it is better to solve this using one design. 

As for current behavior:
It need to be synchronized with Dropdown. 
1. `void select(int)` - indexes from 0 
2. `String selected()` - method is not implemented
3. ` is.selected(String)` - assertion not working as in Dropdown
4. `is()` (`assertThat()`) asserts needs calling `expand()` method to work as expected. 
  (`assertThat().values(contains("Colors", "Red", "Green", "Blue", "Yellow"))`)

**Comment by AlexeyGirin** [comment]
Demo has been done.
