### ISSUE TITLE
Error level codacy issues: Use the overloading mechanism instead of the optional parameters. !!!decide to exclude this pattern

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light-csharp#284]
List of issues: https://app.codacy.com/manual/jdi-testing/jdi-light-csharp/issues?&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W119LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6W119LHsiaWQiOiJMZXZlbCIsInZhbHVlcyI6WyJFcnJvciJdfSx7ImlkIjoiUGF0dGVybiIsInZhbHVlcyI6WyI0MjE5Il19LHsiaWQiOiJBdXRob3IiLCJ2YWx1ZXMiOltdfV0=

1. Learn the problem
2. Fix them if confirmed or suppress otherwise (ask @hellokitties - she know-how)

**Comment by anna-belemenko17** [comment]
Closed as this wouldn't be implemented.

**Comment by AlexeyGirin** [comment]
Decided to ignore pattern

**Comment by AlexeyGirin** [comment]
Demo has been done.
