### ISSUE TITLE
Codacy pattern:Add a 'default' clause to this 'switch' statement.

### ISSUE THREAD

**Issue by tsvetaevAlex** [jdi-testing/jdi-light-csharp#339]
team conclusion to skip pattern

**Comment by tsvetaevAlex** [comment]
issues  List:https://app.codacy.com/manual/jdi-testing/jdi-light-csharp/issues?bid=10276502&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W119LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6W119LHsiaWQiOiJMZXZlbCIsInZhbHVlcyI6WyJFcnJvciJdfSx7ImlkIjoiUGF0dGVybiIsInZhbHVlcyI6WyI0NDE4Il19LHsiaWQiOiJBdXRob3IiLCJ2YWx1ZXMiOltdfV0=

**Comment by tsvetaevAlex** [comment]
["C:\Users\aleksander_tsvetaev\OneDrive - EPAM\tsvetaev.alex\(message updatenew clauses included)RE regarding pattern.msg"](url)

**Comment by AlexeyGirin** [comment]
Demo has been done.
