### ISSUE TITLE
Remove commented code.

### ISSUE THREAD

**Issue by tsvetaevAlex** [jdi-testing/jdi-light-csharp#349]
Fix COdacy WArning Lrvel
pattern:
https://app.codacy.com/manual/jdi-testing/jdi-light-csharp/issues?bid=10276502&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W119LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6W119LHsiaWQiOiJMZXZlbCIsInZhbHVlcyI6W119LHsiaWQiOiJQYXR0ZXJuIiwidmFsdWVzIjpbIjQyNDAiXX0seyJpZCI6IkF1dGhvciIsInZhbHVlcyI6W119XQ==

**Comment by AlexeyGirin** [comment]
Demo has been done.
