### ISSUE TITLE
Create and implement Csharp JDI Light template project.

### ISSUE THREAD

**Issue by anna-belemenko-epam** [jdi-testing/jdi-light-csharp#49]

**Comment by anna-belemenko-epam** [comment]
Implement HasRowWithValues() method in Table.cs for finding particular row in a table that contains several cells with some values in particular columns.

**Comment by anna-belemenko-epam** [comment]
Implement Row() method in Table.cs for finding particular row in a table that contains several cells with some values in particular columns.

**Comment by anna-belemenko-epam** [comment]
Implement Line.cs with GetValue() method.

**Comment by anna-belemenko-epam** [comment]
Implement Preview() method in Table.cs.

**Comment by anna-belemenko-epam** [comment]
Implement Select(string name) method in Dropdown.cs.

**Comment by anna-belemenko-epam** [comment]
Implement Selected() method in Dropdown.cs.

**Comment by anna-belemenko-epam** [comment]
Implement JList<T> class with Select() method, IsSelected() and Selected(string value) methods.

**Comment by AlexeyGirin** [comment]
This task has been decomposed to a number of other tasks - one per each method mentioned in comments to that issue.
This issues no longer needed.
Archived.
